- hosts: webapp


- hosts: balancer
  tasks:
    - name: installing and managing haproxy as a load balancer
      apt: pkg=haproxy state=installed update_cache=true
    
    -name: send our config to balncer server node
     template: src=templates/haproxy.cfg dest=/etc/haproxy/haproxy.cfg mode=0640 owner=root group=root
     notify:
      - restart haproxy

    -name: set haprxy to be started by the init script
     lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
     notify:
      - restart haproxy
  
  handlers:
    - name: restart haproxy service
      service: name=haproxy state=restarted